FROM node

RUN apt-get update
RUN apt-get install -yy wget curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash - && \
	apt-get update && apt-get install -y nodejs && \
  npm i -g npm@6

RUN node -v && npm -v

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
  apt-get update && \
  apt-get install -y google-chrome-stable xvfb
RUN npm -v
RUN apt update && apt install -y procps
RUN apt clean
RUN rm -rf /var/lib/apt/lists/*

# Add a chrome user and setup home dir.
RUN groupadd --system chrome && \
    useradd --system --create-home --gid chrome --groups audio,video chrome && \
    mkdir --parents /home/chrome/reports && \
    chown --recursive chrome:chrome /home/chrome

USER chrome

# Disable Lighthouse error reporting to prevent prompt.
ENV CI=true

# Create app directory
RUN mkdir /usr/src/cloudapp

# Install server dependencies
COPY . /usr/src/cloudapp/
WORKDIR /usr/src/cloudapp/

RUN npm install

RUN ./node_modules/@angular/cli/bin/ng --version

RUN ./node_modules/@angular/cli/bin/ng test --prod 

# Start Node.js Application with server.js
CMD [ "ls" ]   
