FROM node

RUN apt-get update
RUN apt-get install -yy wget curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash - && \
	apt-get update && apt-get install -y nodejs && \
  npm i -g npm@6

RUN node -v && npm -v

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
  apt-get update && \
  apt-get install -y google-chrome-stable xvfb
RUN npm -v
RUN apt update && apt install -y procps
RUN apt clean
RUN rm -rf /var/lib/apt/lists/*



RUN cp out/Debug/chrome_sandbox /usr/local/sbin/chrome-devel-sandbox
RUN chown root:root /usr/local/sbin/chrome-devel-sandbox
RUN chmod 4755 /usr/local/sbin/chrome-devel-sandbox
RUN export CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox

# Disable Lighthouse error reporting to prevent prompt.
ENV CI=true

# Create app directory
RUN mkdir /usr/src/cloudapp

# Install server dependencies
COPY . /usr/src/cloudapp/
WORKDIR /usr/src/cloudapp/
RUN npm install
RUN npm run test 
# Start Node.js Application with server.js
CMD [ "ls" ]   
